from app.schemas.auth import CurrentUser, LoginRequest, TokenResponse
from app.schemas.catalog import (
    AssetTypeCreate,
    AssetTypeOut,
    AssetTypeUpdate,
    PriorityCreate,
    PriorityOut,
    PriorityUpdate,
    WorkOrderStatusOut,
    WorkOrderStatusUpdate,
    WorkOrderTypeCreate,
    WorkOrderTypeOut,
    WorkOrderTypeUpdate,
)
from app.schemas.people import (
    AssetCreate,
    AssetOut,
    AssetUpdate,
    CustomerCreate,
    CustomerOut,
    CustomerUpdate,
    LocationCreate,
    LocationOut,
    LocationUpdate,
    TechnicianCreate,
    TechnicianOut,
    TechnicianUpdate,
)
from app.schemas.tenant import TenantCreate, TenantOut, TenantStatusUpdate
from app.schemas.user import UserCreate, UserOut

__all__ = [
    "AssetCreate",
    "AssetOut",
    "AssetTypeCreate",
    "AssetTypeOut",
    "AssetTypeUpdate",
    "AssetUpdate",
    "CurrentUser",
    "CustomerCreate",
    "CustomerOut",
    "CustomerUpdate",
    "LocationCreate",
    "LocationOut",
    "LocationUpdate",
    "LoginRequest",
    "PriorityCreate",
    "PriorityOut",
    "PriorityUpdate",
    "TechnicianCreate",
    "TechnicianOut",
    "TechnicianUpdate",
    "TenantCreate",
    "TenantOut",
    "TenantStatusUpdate",
    "TokenResponse",
    "UserCreate",
    "UserOut",
    "WorkOrderStatusOut",
    "WorkOrderStatusUpdate",
    "WorkOrderTypeCreate",
    "WorkOrderTypeOut",
    "WorkOrderTypeUpdate",
]