"""email unico global para PLATFORM_OWNER

Revision ID: 39e3c7fbd7a6
Revises: 8272b92801ea
Create Date: 2026-08-21 23:55:43.797376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e3c7fbd7a6'
down_revision: Union[str, Sequence[str], None] = '8272b92801ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate no detecta cambios de predicado WHERE en índices
    # existentes: se recrea manualmente ix_users_tenant_email como parcial
    # (tenant_id IS NOT NULL) para dejar de superponerse con el nuevo
    # índice único parcial de PLATFORM_OWNER (tenant_id IS NULL).
    op.drop_index('ix_users_tenant_email', table_name='users')
    op.create_index(
        'ix_users_tenant_email',
        'users',
        ['tenant_id', 'email'],
        unique=True,
        sqlite_where=sa.text('tenant_id IS NOT NULL'),
        postgresql_where=sa.text('tenant_id IS NOT NULL'),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_platform_owner_email', 'users', ['email'], unique=True, sqlite_where=sa.text('tenant_id IS NULL'), postgresql_where=sa.text('tenant_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_platform_owner_email', table_name='users', sqlite_where=sa.text('tenant_id IS NULL'), postgresql_where=sa.text('tenant_id IS NULL'))
    # ### end Alembic commands ###

    op.drop_index('ix_users_tenant_email', table_name='users')
    op.create_index(
        'ix_users_tenant_email',
        'users',
        ['tenant_id', 'email'],
        unique=True,
    )
