"""etapa 04 nucleo OT work_orders y work_order_history

Revision ID: 46e438c0af67
Revises: 83ddbdb4ede8
Create Date: 2026-08-22 11:18:32.530308

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46e438c0af67"
down_revision: str | Sequence[str] | None = "83ddbdb4ede8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("technician_id", sa.Uuid(), nullable=True),
        sa.Column("work_order_type_id", sa.Uuid(), nullable=False),
        sa.Column("priority_id", sa.Uuid(), nullable=False),
        sa.Column("status_id", sa.Uuid(), nullable=False),
        sa.Column("requested_description", sa.Text(), nullable=False),
        sa.Column("performed_description", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["priorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["work_order_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "technician_id"],
            ["technicians.tenant_id", "technicians.person_id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_type_id"],
            ["work_order_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_work_orders_tenant_id"),
        sa.UniqueConstraint("tenant_id", "number", name="uq_work_orders_tenant_number"),
    )
    op.create_index(
        op.f("ix_work_orders_asset_id"), "work_orders", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_location_id"), "work_orders", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_tenant_id"), "work_orders", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_work_orders_tenant_status",
        "work_orders",
        ["tenant_id", "status_id"],
        unique=False,
    )
    op.create_index(
        "ix_work_orders_tenant_technician",
        "work_orders",
        ["tenant_id", "technician_id"],
        unique=False,
    )
    op.create_table(
        "work_order_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CREATED",
                "ASSIGNED",
                "STATUS_CHANGE",
                "REOPENED",
                name="historyeventtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("previous_value", sa.String(length=100), nullable=True),
        sa.Column("new_value", sa.String(length=100), nullable=True),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["work_order_id"], ["work_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_order_history_tenant_id"),
        "work_order_history",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_work_order_history_tenant_wo",
        "work_order_history",
        ["tenant_id", "work_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_work_order_history_tenant_wo", table_name="work_order_history")
    op.drop_index(
        op.f("ix_work_order_history_tenant_id"), table_name="work_order_history"
    )
    op.drop_table("work_order_history")
    op.drop_index("ix_work_orders_tenant_technician", table_name="work_orders")
    op.drop_index("ix_work_orders_tenant_status", table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_tenant_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_location_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_asset_id"), table_name="work_orders")
    op.drop_table("work_orders")
    # ### end Alembic commands ###
