"""catalogos parametrizables tipos de activo tipos de trabajo prioridades estados de ot

Revision ID: 60f3bb6e6fa3
Revises: 39e3c7fbd7a6
Create Date: 2026-08-22 00:10:53.852621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f3bb6e6fa3'
down_revision: Union[str, Sequence[str], None] = '39e3c7fbd7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_asset_types_tenant_code')
    )
    op.create_index(op.f('ix_asset_types_tenant_id'), 'asset_types', ['tenant_id'], unique=False)
    op.create_table('priorities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_priorities_tenant_code')
    )
    op.create_index(op.f('ix_priorities_tenant_id'), 'priorities', ['tenant_id'], unique=False)
    op.create_table('work_order_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_work_order_statuses_tenant_code')
    )
    op.create_index(op.f('ix_work_order_statuses_tenant_id'), 'work_order_statuses', ['tenant_id'], unique=False)
    op.create_table('work_order_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_work_order_types_tenant_code')
    )
    op.create_index(op.f('ix_work_order_types_tenant_id'), 'work_order_types', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_types_tenant_id'), table_name='work_order_types')
    op.drop_table('work_order_types')
    op.drop_index(op.f('ix_work_order_statuses_tenant_id'), table_name='work_order_statuses')
    op.drop_table('work_order_statuses')
    op.drop_index(op.f('ix_priorities_tenant_id'), table_name='priorities')
    op.drop_table('priorities')
    op.drop_index(op.f('ix_asset_types_tenant_id'), table_name='asset_types')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
