"""etapa 06 mobile pwa: technician user_id y work_order_photos

Revision ID: 6d1d48d98e24
Revises: 46e438c0af67
Create Date: 2026-08-22 20:38:35.560564

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d1d48d98e24"
down_revision: str | Sequence[str] | None = "46e438c0af67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_order_photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("caption", sa.String(length=255), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"], ["work_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_order_photos_tenant_id"),
        "work_order_photos",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_work_order_photos_tenant_wo",
        "work_order_photos",
        ["tenant_id", "work_order_id"],
        unique=False,
    )
    with op.batch_alter_table("technicians", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Uuid(), nullable=True))
        batch_op.create_index("ix_technicians_user_id", ["user_id"], unique=True)
        batch_op.create_foreign_key(
            "fk_technicians_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("technicians", schema=None) as batch_op:
        batch_op.drop_constraint("fk_technicians_user_id_users", type_="foreignkey")
        batch_op.drop_index("ix_technicians_user_id")
        batch_op.drop_column("user_id")
    op.drop_index("ix_work_order_photos_tenant_wo", table_name="work_order_photos")
    op.drop_index(
        op.f("ix_work_order_photos_tenant_id"), table_name="work_order_photos"
    )
    op.drop_table("work_order_photos")
    # ### end Alembic commands ###
