"""etapa_03_maestros_fix_indexes

Revision ID: 83ddbdb4ede8
Revises: d4e7bd9fe8e8
Create Date: 2026-08-22 02:22:52.813105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ddbdb4ede8'
down_revision: Union[str, Sequence[str], None] = 'd4e7bd9fe8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
