"""etapa_03_maestros_person_customer_technician_location_asset

Revision ID: d4e7bd9fe8e8
Revises: edac9c5ce83f
Create Date: 2026-08-22 01:56:05.311278

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4e7bd9fe8e8"
down_revision: str | Sequence[str] | None = "edac9c5ce83f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "person_type",
            sa.Enum("INDIVIDUAL", "LEGAL", name="persontype", native_enum=False),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="personstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_people_tenant_id"),
    )
    op.create_index(
        "ix_people_display_name", "people", ["tenant_id", "display_name"], unique=False
    )
    op.create_index(op.f("ix_people_tenant_id"), "people", ["tenant_id"], unique=False)
    op.create_table(
        "customers",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "person_id"],
            ["people.tenant_id", "people.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "person_id"),
    )
    op.create_index("ix_customers_tenant_id", "customers", ["tenant_id"], unique=False)
    op.create_table(
        "person_identifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("identification_type", sa.String(length=50), nullable=False),
        sa.Column("identification_value", sa.String(length=50), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "country_code",
            "identification_type",
            "identification_value",
            name="uq_person_identifications_tenant_country_type_value",
        ),
    )
    op.create_index(
        op.f("ix_person_identifications_person_id"),
        "person_identifications",
        ["person_id"],
        unique=False,
    )
    op.create_index(
        "ix_person_identifications_tenant_id",
        "person_identifications",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "technicians",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("profession", sa.String(length=100), nullable=True),
        sa.Column("license_number", sa.String(length=50), nullable=True),
        sa.Column("commission_percentage", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="technicianstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "person_id"],
            ["people.tenant_id", "people.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "person_id"),
    )
    op.create_index(
        "ix_technicians_status", "technicians", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        "ix_technicians_tenant_id", "technicians", ["tenant_id"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("province", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.person_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "customer_id", "name", name="uq_locations_tenant_customer_name"
        ),
    )
    op.create_index(
        "ix_locations_customer_id", "locations", ["customer_id"], unique=False
    )
    op.create_index("ix_locations_tenant_id", "locations", ["tenant_id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("asset_type_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("internal_code", sa.String(length=50), nullable=True),
        sa.Column("qr_code", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", "RETIRED", name="assetstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_type_id"], ["asset_types.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assets_asset_type_id"), "assets", ["asset_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_assets_location_id"), "assets", ["location_id"], unique=False
    )
    op.create_index(
        "ix_assets_qr_code", "assets", ["tenant_id", "qr_code"], unique=True
    )
    op.create_index("ix_assets_tenant_id", "assets", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_assets_tenant_id", table_name="assets")
    op.drop_index("ix_assets_qr_code", table_name="assets")
    op.drop_index(op.f("ix_assets_location_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_type_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index("ix_locations_tenant_id", table_name="locations")
    op.drop_index("ix_locations_customer_id", table_name="locations")
    op.drop_table("locations")
    op.drop_index("ix_technicians_tenant_id", table_name="technicians")
    op.drop_index("ix_technicians_status", table_name="technicians")
    op.drop_table("technicians")
    op.drop_index(
        "ix_person_identifications_tenant_id", table_name="person_identifications"
    )
    op.drop_index(
        op.f("ix_person_identifications_person_id"), table_name="person_identifications"
    )
    op.drop_table("person_identifications")
    op.drop_index("ix_customers_tenant_id", table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_people_tenant_id"), table_name="people")
    op.drop_index("ix_people_display_name", table_name="people")
    op.drop_table("people")
    # ### end Alembic commands ###
