"""plantillas de configuracion inicial por tenant

Revision ID: edac9c5ce83f
Revises: 60f3bb6e6fa3
Create Date: 2026-08-22 00:26:07.000807

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edac9c5ce83f'
down_revision: Union[str, Sequence[str], None] = '60f3bb6e6fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contenido de la plantilla DEFAULT — debe coincidir con
# `tests/helpers.py::seed_default_config_template` para que tests y
# esquema real no diverjan.
_DEFAULT_TEMPLATE_PRIORITIES = [
    ('LOW', 'Baja', 1),
    ('NORMAL', 'Normal', 2),
    ('HIGH', 'Alta', 3),
    ('URGENT', 'Urgente', 4),
]
_DEFAULT_TEMPLATE_WORK_ORDER_TYPES = [
    ('CORRECTIVE', 'Correctivo'),
    ('PREVENTIVE', 'Preventivo'),
    ('INSTALLATION', 'Instalación'),
    ('REVIEW', 'Revisión'),
    ('INSPECTION', 'Inspección'),
    ('WARRANTY', 'Garantía'),
]
_DEFAULT_TEMPLATE_WORK_ORDER_STATUSES = [
    ('PENDING', 'Pendiente', False),
    ('IN_PROGRESS', 'En proceso', False),
    ('COMPLETED', 'Terminada', True),
    ('UNRESOLVED', 'No resuelta', True),
]
_DEFAULT_TEMPLATE_ASSET_TYPES = [
    ('EQUIPMENT', 'Equipo'),
    ('INSTALLATION', 'Instalación'),
    ('OTHER', 'Otro'),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_templates_code'), 'config_templates', ['code'], unique=True)
    op.create_table('template_asset_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['config_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_template_asset_types_template_code')
    )
    op.create_index(op.f('ix_template_asset_types_template_id'), 'template_asset_types', ['template_id'], unique=False)
    op.create_table('template_priorities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['config_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_template_priorities_template_code')
    )
    op.create_index(op.f('ix_template_priorities_template_id'), 'template_priorities', ['template_id'], unique=False)
    op.create_table('template_work_order_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['config_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_template_work_order_statuses_template_code')
    )
    op.create_index(op.f('ix_template_work_order_statuses_template_id'), 'template_work_order_statuses', ['template_id'], unique=False)
    op.create_table('template_work_order_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['config_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_template_work_order_types_template_code')
    )
    op.create_index(op.f('ix_template_work_order_types_template_id'), 'template_work_order_types', ['template_id'], unique=False)
    # ### end Alembic commands ###

    # Semilla de la plantilla DEFAULT — única existente en el MVP; el modelo
    # admite agregar plantillas por rubro en el futuro (docs/tecnica/modelo-datos.md §9).
    config_templates_table = sa.table(
        'config_templates',
        sa.column('id', sa.Uuid),
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('active', sa.Boolean),
    )
    template_priorities_table = sa.table(
        'template_priorities',
        sa.column('id', sa.Uuid),
        sa.column('template_id', sa.Uuid),
        sa.column('code', sa.String),
        sa.column('label', sa.String),
        sa.column('sort_order', sa.Integer),
    )
    template_work_order_types_table = sa.table(
        'template_work_order_types',
        sa.column('id', sa.Uuid),
        sa.column('template_id', sa.Uuid),
        sa.column('code', sa.String),
        sa.column('label', sa.String),
    )
    template_work_order_statuses_table = sa.table(
        'template_work_order_statuses',
        sa.column('id', sa.Uuid),
        sa.column('template_id', sa.Uuid),
        sa.column('code', sa.String),
        sa.column('label', sa.String),
        sa.column('is_terminal', sa.Boolean),
    )
    template_asset_types_table = sa.table(
        'template_asset_types',
        sa.column('id', sa.Uuid),
        sa.column('template_id', sa.Uuid),
        sa.column('code', sa.String),
        sa.column('label', sa.String),
    )

    default_template_id = uuid.uuid4()
    op.bulk_insert(
        config_templates_table,
        [{'id': default_template_id, 'code': 'DEFAULT', 'name': 'Configuración estándar', 'active': True}],
    )
    op.bulk_insert(
        template_priorities_table,
        [
            {'id': uuid.uuid4(), 'template_id': default_template_id, 'code': code, 'label': label, 'sort_order': sort_order}
            for code, label, sort_order in _DEFAULT_TEMPLATE_PRIORITIES
        ],
    )
    op.bulk_insert(
        template_work_order_types_table,
        [
            {'id': uuid.uuid4(), 'template_id': default_template_id, 'code': code, 'label': label}
            for code, label in _DEFAULT_TEMPLATE_WORK_ORDER_TYPES
        ],
    )
    op.bulk_insert(
        template_work_order_statuses_table,
        [
            {'id': uuid.uuid4(), 'template_id': default_template_id, 'code': code, 'label': label, 'is_terminal': is_terminal}
            for code, label, is_terminal in _DEFAULT_TEMPLATE_WORK_ORDER_STATUSES
        ],
    )
    op.bulk_insert(
        template_asset_types_table,
        [
            {'id': uuid.uuid4(), 'template_id': default_template_id, 'code': code, 'label': label}
            for code, label in _DEFAULT_TEMPLATE_ASSET_TYPES
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_work_order_types_template_id'), table_name='template_work_order_types')
    op.drop_table('template_work_order_types')
    op.drop_index(op.f('ix_template_work_order_statuses_template_id'), table_name='template_work_order_statuses')
    op.drop_table('template_work_order_statuses')
    op.drop_index(op.f('ix_template_priorities_template_id'), table_name='template_priorities')
    op.drop_table('template_priorities')
    op.drop_index(op.f('ix_template_asset_types_template_id'), table_name='template_asset_types')
    op.drop_table('template_asset_types')
    op.drop_index(op.f('ix_config_templates_code'), table_name='config_templates')
    op.drop_table('config_templates')
    # ### end Alembic commands ###
